# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

School.find_or_create_by_name "Sierra community College"
School.find_or_create_by_name "American River College"
School.find_or_create_by_name "California Maritime Academy, (Vallejo)"
School.find_or_create_by_name "California Polytechnic State University, (San Luis Obispo)"
School.find_or_create_by_name "California State Polytechnic University, Pomona"
School.find_or_create_by_name "California State University, Bakersfield, (Bakersfield)"
School.find_or_create_by_name "California State University, Channel Islands,(Camarillo)"
School.find_or_create_by_name "California State University, Chico, (Chico)"
School.find_or_create_by_name "California State University, Dominguez Hills, (Carson)"
School.find_or_create_by_name "California State University, East Bay, (Hayward)"
School.find_or_create_by_name "California State University, Fresno, (Fresno)"
School.find_or_create_by_name "California State University, Fullerton, (Fullerton)"
School.find_or_create_by_name "California State University, Long Beach, (Long Beach)"
School.find_or_create_by_name "California State University, Los Angeles, (Los Angeles)"
School.find_or_create_by_name "California State University, Monterey Bay"
School.find_or_create_by_name "California State University, Northridge"
School.find_or_create_by_name "California State University, Sacramento"
School.find_or_create_by_name "California State University, San Bernardino"
School.find_or_create_by_name "California State University, San Marcos"
School.find_or_create_by_name "California State University, Stanislaus"
School.find_or_create_by_name "Humboldt State University"
School.find_or_create_by_name "San Diego State University"
School.find_or_create_by_name "San Francisco State University"
School.find_or_create_by_name " San Jose State University"
School.find_or_create_by_name " Sonoma State University"
School.find_or_create_by_name "University of California, Berkeley"
School.find_or_create_by_name "University of California, Davis"
School.find_or_create_by_name "University of California, Irvine"
School.find_or_create_by_name "University of California, Los Angeles "
School.find_or_create_by_name "University of California, Merced "
School.find_or_create_by_name "University of California, Riverside"
School.find_or_create_by_name  "University of California, Riverside"
School.find_or_create_by_name  "University of California, San Francisco"
School.find_or_create_by_name "University of California, Santa Barbara"
School.find_or_create_by_name "University of California, Santa Cruz"
School.find_or_create_by_name "Academy of Art University, San Francisco"
School.find_or_create_by_name "Allied American University, Laguna Hills "
School.find_or_create_by_name "American Heritage University of Southern California"
School.find_or_create_by_name  "American Jewish University, Los Angeles"
School.find_or_create_by_name  "American Sports University, San Bernardino"
School.find_or_create_by_name  "Anaheim University"
School.find_or_create_by_name  "Antioch University, Culver City"
School.find_or_create_by_name  "Apollos University, Huntington Beach"
School.find_or_create_by_name "Argosy University,Alameda"
School.find_or_create_by_name  "Art Center College of Design, Pasadena"
School.find_or_create_by_name  "The Art Institute of California,San Francisco"
School.find_or_create_by_name  "Azusa Pacific University"
School.find_or_create_by_name  "Bethany University, Scotts Valley"
School.find_or_create_by_name "Biola University, La Mirada"
School.find_or_create_by_name  "Brooks Institute, Santa Barbara"
School.find_or_create_by_name  "California Baptist University, Riverside"
School.find_or_create_by_name  "California Coast University, Santa Ana"
School.find_or_create_by_name  "California College of the Arts, San Francisco"
School.find_or_create_by_name  "California College San Diego (CCSD),"
School.find_or_create_by_name  "California Institute of the Arts, Valencia"
School.find_or_create_by_name  "California Institute of Integral Studies, San Francisco"
School.find_or_create_by_name  "California Institute of Technology, Pasadena"
School.find_or_create_by_name  "California InterContinental University, Diamond Bar"
School.find_or_create_by_name  "California Lutheran University, Thousand Oaks"
School.find_or_create_by_name  "California Miramar University"
School.find_or_create_by_name  "California National University, Northridge"
School.find_or_create_by_name  "California Pacific University, Escondido"
School.find_or_create_by_name  "California South Bay University, Sunnyvale"
School.find_or_create_by_name  "California South University, Irvine"
School.find_or_create_by_name  "California Southern Law School"
School.find_or_create_by_name  "California Southern University, Santa Ana(ONLINE)"
School.find_or_create_by_name  "California Takshila University,Santa Clara"
School.find_or_create_by_name  "California University of Management and Technology"
School.find_or_create_by_name  "California University of Management and Sciences"
School.find_or_create_by_name  "Capital Bible College, Sacramento"
School.find_or_create_by_name  "CapStone University, Pasadena (online)"
School.find_or_create_by_name  "Carnegie Mellon Silicon Valley Campus"
School.find_or_create_by_name  "Chapman University, Orange"
School.find_or_create_by_name  "Charles R. Drew University of Medicine and Science"
School.find_or_create_by_name  "Claremont Colleges, Claremont"
School.find_or_create_by_name  "Claremont McKenna College"
School.find_or_create_by_name  "Harvey Mudd College"
School.find_or_create_by_name "Pitzer College"
School.find_or_create_by_name  "Pomona College"
School.find_or_create_by_name  "Scripps College"
School.find_or_create_by_name  "Claremont Graduate University"
School.find_or_create_by_name  "Cogswell College, Sunnyvale"
School.find_or_create_by_name  "Concordia University Irvine"
School.find_or_create_by_name  "Culinary Institute of America at Greystone"
School.find_or_create_by_name  "Dominican University of California, San Rafael"
School.find_or_create_by_name  "Design Institute of San Diego"
School.find_or_create_by_name  "Epic Bible College (formerly Trinity Life Bible College)"
School.find_or_create_by_name  "Fresno Pacific University, Fresno"
School.find_or_create_by_name  "Fuller Theological Seminary, Pasadena"
School.find_or_create_by_name  "Golden Gate University, San Francisco"
School.find_or_create_by_name  "Herguan University, Sunnyvale"
School.find_or_create_by_name  "Holy Names University, Oakland"
School.find_or_create_by_name  "Hope International University, Fullerton"
School.find_or_create_by_name  "Hult International Business School, San Francisco"
School.find_or_create_by_name   "Humphreys College, Stockton"
School.find_or_create_by_name   "Imago Dei College, Oak Glen"
School.find_or_create_by_name   "Imago Dei College, Oak Glen"
School.find_or_create_by_name   "John Paul the Great Catholic University, San Diego"
School.find_or_create_by_name   "Laguna College of Art and Design, Laguna Beach"
School.find_or_create_by_name   "La Sierra University, Riverside"
School.find_or_create_by_name   "Life Pacific College, San Dimas"
School.find_or_create_by_name   "Lincoln University, Oakland"
School.find_or_create_by_name   "Loma Linda University, Loma Linda"
School.find_or_create_by_name  "Loyola Marymount University, Los Angeles"
School.find_or_create_by_name   "Master's College, Newhall"
School.find_or_create_by_name   "Mayfield College, Cathedral City"
School.find_or_create_by_name   "Menlo College, Atherton"
School.find_or_create_by_name   "Mills College, Oakland"
School.find_or_create_by_name "Monsbey College, Watsonville"
School.find_or_create_by_name  "Monterey Institute of International Studies, Monterey"
School.find_or_create_by_name   "Mount St. Mary's College, Los Angeles"
School.find_or_create_by_name   "National Hispanic University, San Jose"
School.find_or_create_by_name   "National University, San Diego"
School.find_or_create_by_name   "NewSchool of Architecture and Design, San Diego"
School.find_or_create_by_name   "Northern Coastal College, Crescent City"
School.find_or_create_by_name   "Northwestern Polytechnic University, Fremont"
School.find_or_create_by_name   "Notre Dame de Namur University, Belmont"
School.find_or_create_by_name   "Occidental College, Los Angeles"
School.find_or_create_by_name   "Otis College of Art and Design, Los Angeles"
School.find_or_create_by_name   "Pacific Oaks College, Pasadena"
School.find_or_create_by_name   "Pacific Union College, Angwin"
School.find_or_create_by_name   "Patten College, Oakland"
School.find_or_create_by_name   "Pepperdine University, Malibu"
School.find_or_create_by_name   "Point Loma Nazarene University, San Diego"
School.find_or_create_by_name   "San Francisco Institute of Architecture, Berkeley"
School.find_or_create_by_name   "Saint Mary's College of California, Moraga"
School.find_or_create_by_name   "Samuel Merritt University, Oakland"
School.find_or_create_by_name   "San Diego Christian College, El Cajon"
School.find_or_create_by_name   "San Joaquin College of Law, Clovis"
School.find_or_create_by_name   "San Luis Rey College, Oceanside"
School.find_or_create_by_name   "Santa Clara University, Santa Clara"
School.find_or_create_by_name   "Silicon Valley University, San Jose"
School.find_or_create_by_name   "Simpson University, Redding"
School.find_or_create_by_name   "Soka University of America, Aliso Viejo"
School.find_or_create_by_name   "Southern California Institute of Architecture, Los Angeles"
School.find_or_create_by_name   "St. Mary's College of California, Moraga"
School.find_or_create_by_name   "Stanford University, Stanford"
School.find_or_create_by_name   "Thomas Aquinas College, Santa Paula"
School.find_or_create_by_name   "Trinity International University"
School.find_or_create_by_name  "Touro University, Vallejo"
School.find_or_create_by_name   "TUI University, Cypress (Online)"
School.find_or_create_by_name   "University of La Verne, La Verne"
School.find_or_create_by_name   "University of Northern California, Santa Rosa"
School.find_or_create_by_name   "UNC, Lorenzo Patiño School of Law"
School.find_or_create_by_name   "University of Redlands, Redlands"
School.find_or_create_by_name   "University of the Pacific, Stockton"
School.find_or_create_by_name   "University of San Diego, San Diego"
School.find_or_create_by_name   "University of San Francisco"
School.find_or_create_by_name   "University of Southern California, Los Angeles"
School.find_or_create_by_name   "University of West Los Angeles"
School.find_or_create_by_name  "University of West Los Angeles, Inglewood"
School.find_or_create_by_name   "University of West Los Angeles,Woodland Hills"
School.find_or_create_by_name   "University of the West, Rosemead"
School.find_or_create_by_name   "Vanguard University of Southern California, Costa Mesa"
School.find_or_create_by_name  "Western Institute for Social Research, Berkeley"
School.find_or_create_by_name   "Westmont College, Santa Barbara"
School.find_or_create_by_name   "Whittier College, Whittier"
School.find_or_create_by_name   "William Howard Taft University, Santa Ana"
School.find_or_create_by_name   "William Jessup University, Rocklin"
School.find_or_create_by_name   "Woodbury University, Burbank"
School.find_or_create_by_name  "Allan Hancock College "
School.find_or_create_by_name  "Antelope Valley College"
School.find_or_create_by_name   "Chaffey College "
School.find_or_create_by_name   "Barstow College"
School.find_or_create_by_name   "Butte College"
School.find_or_create_by_name   "Citrus College "
School.find_or_create_by_name   "Coastline Community College"
School.find_or_create_by_name   "Golden West  College "
School.find_or_create_by_name   "Feather River College"
School.find_or_create_by_name   "Orange Coast College "
School.find_or_create_by_name   "Compton Community college "
School.find_or_create_by_name   "College of the Desert "
School.find_or_create_by_name   "El Camino College "
School.find_or_create_by_name   "De Anza College"
School.find_or_create_by_name   "Foothill College "
School.find_or_create_by_name   "Gavilan College "
School.find_or_create_by_name   "Glendale Community College"
School.find_or_create_by_name   "Cuyamaca College"
School.find_or_create_by_name   "Grossmont College "
School.find_or_create_by_name   "Hartnell College "
School.find_or_create_by_name   "Imperial Valley College "
School.find_or_create_by_name   "Bakersfield College"
School.find_or_create_by_name   "Cerro Coso Community college "
School.find_or_create_by_name   "Porterville College"
School.find_or_create_by_name   "Lake Tahoe Community College "
School.find_or_create_by_name   "Lassen College"
School.find_or_create_by_name   "Long Beach City College "
School.find_or_create_by_name   "East LA College"
School.find_or_create_by_name   "LA City College"
School.find_or_create_by_name   "LA Harbor College"
School.find_or_create_by_name   "LA Mission College"
School.find_or_create_by_name   "LA Pierce College"
School.find_or_create_by_name   "LA Southwest College"
School.find_or_create_by_name   "LA Trade-Tech College"
School.find_or_create_by_name   "LA Valley College"
School.find_or_create_by_name   "West LA College "
School.find_or_create_by_name   "American River College"
School.find_or_create_by_name   "Consumnes River College"
School.find_or_create_by_name   "Folsom Lake College"
School.find_or_create_by_name   "Sacramento City College"
School.find_or_create_by_name   "College of Marin"
School.find_or_create_by_name   "College of Marin "
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name
School.find_or_create_by_name   
School.find_or_create_by_name   
School.find_or_create_by_name



major.find_or_create_by_name "undeclared"
major.find_or_create_by_name "Architectural Design"
major.find_or_create_by_name "Art and Design"
major.find_or_create_by_name "Administration of justice"
major.find_or_create_by_name "Atmosphere and Energy"
major.find_or_create_by_name "Aeronautics and Astronautics"
major.find_or_create_by_name "Computer science"
major.find_or_create_by_name "African American Studies"
major.find_or_create_by_name "American Cultures"
major.find_or_create_by_name "Chemical Engineering"
major.find_or_create_by_name "Mechanical Engineering"
major.find_or_create_by_name "Envronmental Engineering"
major.find_or_create_by_name "Political science"
major.find_or_create_by_name "Bioengineering" 
major.find_or_create_by_name "Biomechanical Engineering"
major.find_or_create_by_name "Civil Engineering"
major.find_or_create_by_name "Electrical Engineering"
major.find_or_create_by_name "Physics"
major.find_or_create_by_name  "Anthropology"
major.find_or_create_by_name "Archaeology"
major.find_or_create_by_name "History"
major.find_or_create_by_name  "Film and Media Studies"
major.find_or_create_by_name  "Asian American Studies"
major.find_or_create_by_name  "Biology"
major.find_or_create_by_name  "Chemistry"
major.find_or_create_by_name "Communication"
major.find_or_create_by_name  "Drama"
major.find_or_create_by_name  "Economics"
major.find_or_create_by_name  "English"
major.find_or_create_by_name  "French"
major.find_or_create_by_name  "Philosophy"
major.find_or_create_by_name  "Mathematics"
major.find_or_create_by_name  "Music"
major.find_or_create_by_name  "Psychology"
major.find_or_create_by_name  "Sociology"
major.find_or_create_by_name  "Astronomy"
major.find_or_create_by_name  "Agricultural"
major.find_or_create_by_name  "Business"
major.find_or_create_by_name  "Literature"
major.find_or_create_by_name  "Classics" 
major.find_or_create_by_name  "Cognitive Science"
major.find_or_create_by_name  "Law"
major.find_or_create_by_name  "Ethnic Studies"
major.find_or_create_by_name  "Education"
major.find_or_create_by_name  "Forestry and Natural Resources"
major.find_or_create_by_name  "Gender and Women's Studies"
major.find_or_create_by_name  "Geography"
major.find_or_create_by_name  "Geology & Geophysics"
major.find_or_create_by_name  "Health Sciences"
major.find_or_create_by_name  "Journalism"
major.find_or_create_by_name  "Liberal Arts"
major.find_or_create_by_name  "Microbiology"
major.find_or_create_by_name  "Native American Studies"
major.find_or_create_by_name  "Neurobiology"
major.find_or_create_by_name  "Neuroscience"
major.find_or_create_by_name  "Nuclear Engineering"
major.find_or_create_by_name  "Nutrition/Nutritional Sciences"
major.find_or_create_by_name  "Physical Education"
major.find_or_create_by_name  "Public Health"
major.find_or_create_by_name  "Social Sciences"
major.find_or_create_by_name  "Spanish"
major.find_or_create_by_name  "Statistics"
